package com.laa66.goodboi.command;

public enum CommandType {
    PUSH_MESSAGE,
    ZAHIR_MESSAGE,
    JOIN_CHANNEL,
    EXIT_CHANNEL,
    PLAY_MUSIC,
    STOP_MUSIC,
    RESUME_MUSIC,
    SKIP_MUSIC,
    CLEAN_SCHEDULER,
    PRINT_QUEUE,
    COMMAND_INFO,
    BANNED_USERS,
    WARNED_USERS,
    RUDEST_USERS,
    GUILD_VOICE_ACTIVITY
}
