version: "3.8"
services:
  goodboi_service:
    build: .
    restart: always
    environment:
      GOODBOI_DISCORD_TOKEN: ${GOODBOI_DISCORD_TOKEN}
      GOODBOI_GUILD_ID: ${GOODBOI_GUILD_ID}
      GOODBOI_DB_USERNAME: postgres
      GOODBOI_DB_PASSWORD: password
      GOODBOI_DB_URL: r2dbc:postgresql://db:5432/goodboi_db?allowPublicKeyRetrieval=true&useSSL=true
    volumes:
      - .m2:/root/.m2
    networks:
      - goodboi-net

  db:
    image: "postgres:15"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=goodboi_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - goodboi-net

networks:
  goodboi-net:

