# discord
bot:
  discord:
    token: ${GOODBOI_DISCORD_TOKEN}
    dev:
      guild-id: ${GOODBOI_GUILD_ID}

# database
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/goodboi_bot_db?allowPublicKeyRetrieval=true&useSSL=true
    username: ${GOODBOI_DB_USERNAME}
    password: ${GOODBO_DB_PASSWORD}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50

logging:
  level:
    org:
      springframework: INFO
