# discord
bot:
  discord:
    token: ${GOODBOI_DISCORD_TOKEN}
    dev:
      guild-id: ${GOODBOI_GUILD_ID}

# database
spring:
  r2dbc:
    url: ${GOODBOI_DB_URL}
    username: ${GOODBOI_DB_USERNAME}
    password: ${GOODBOI_DB_PASSWORD}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50

logging:
  level:
    org:
      springframework: INFO
